FROM nginx:latest

COPY ./packages/client/nginx.conf /etc/nginx/nginx.conf
COPY ./packages/client/certs/privkey1.pem /etc/ssl/privkey.pem
COPY ./packages/client/certs/cert1.pem /etc/ssl/cert.pem

EXPOSE 80
EXPOSE 443

CMD [ "nginx", "-g", "daemon off;" ]
