export const DEV_CLIENT_PATH = 'http://localhost:3000'
export const DEV_BACKEND_PATH = 'http://localhost:3001'
export const PROD_CLIENT_PATH = 'https://zukva.ya-praktikum.tech'
export const PROD_BACKEND_PATH = 'https://zukva.ya-praktikum.tech'
export const TEAM_NAME = 'zukva'
